### ISSUE TITLE
RangeError: Invalid status code: 1

### ISSUE THREAD

**Issue by govindrai** [sass/node-sass-middleware#108]
This piece of code 

```
app.use(sassMiddleware({
  src: path.join(__dirname, 'public'),
  dest: path.join(__dirname, 'public'),
  indentedSyntax: true, // true = .sass and false = .scss
  sourceMap: true
}));
```

is causing the following error:

```
RangeError: Invalid status code: 1
    at ServerResponse.writeHead (_http_server.js:195:11)
    at ServerResponse.writeHead (/Users/raigovind93/LPN-Fitness-App/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (/Users/raigovind93/LPN-Fitness-App/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:159:8)
    at ServerResponse.end (_http_outgoing.js:621:10)
    at ServerResponse.end (/Users/raigovind93/LPN-Fitness-App/node_modules/express-session/index.js:354:19)
    at ServerResponse.send (/Users/raigovind93/LPN-Fitness-App/node_modules/express/lib/response.js:211:10)
    at done (/Users/raigovind93/LPN-Fitness-App/node_modules/express/lib/response.js:967:10)
    at Object.exports.renderFile (/Users/raigovind93/LPN-Fitness-App/node_modules/pug/lib/index.js:422:12)
    at View.exports.__express [as engine] (/Users/raigovind93/LPN-Fitness-App/node_modules/pug/lib/index.js:465:11)
    at View.render (/Users/raigovind93/LPN-Fitness-App/node_modules/express/lib/view.js:128:8)
    at tryRender (/Users/raigovind93/LPN-Fitness-App/node_modules/express/lib/application.js:640:10)
    at Function.render (/Users/raigovind93/LPN-Fitness-App/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/raigovind93/LPN-Fitness-App/node_modules/express/lib/response.js:971:7)
    at /Users/raigovind93/LPN-Fitness-App/app.js:97:7
    at Layer.handle_error (/Users/raigovind93/LPN-Fitness-App/node_modules/express/lib/router/layer.js:71:5)
```

Could this be because the build is failing?

Here is my dependency in my package.json:

```
...
    "node-sass-middleware": "^0.9.8"
...
```

**Comment by govindrai** [comment]
Anyone?

**Comment by nschonni** [comment]
You mention this happens when you add `node-sass`, but nothing in the log information indicates the error is bubbling from there.
Can you confirm what version of Node and node-sass you're running?

**Comment by govindrai** [comment]
Hi Nick, I finally figured it out... it was because I had a SASS syntax error, and `debug: true` helped me out. Still I feel like the non-compilation should throw a more helpful message..

**Comment by nil96** [comment]
@govindrai I didn't get how you figured it out I am struggling with the same issue.your suggestion will be helpful

**Comment by Emyboy** [comment]
i have a similar problem . but its when i created a PUT request with knex i always retured " Unhandled rejection RangeError 1 " please any solution  ?
