### ISSUE TITLE
node scripts/build.js failing

### ISSUE THREAD

**Issue by causztic** [sass/node-sass-middleware#26]
Hi,

I'm trying to install node-sass-middleware with npm and a error occured:

    Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/causztic/Work/grafiore/node_modules/node-sass-middleware/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

    npm ERR! Darwin 14.1.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-sass-middleware"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1
    npm ERR! code ELIFECYCLE

Any ideas?

**Comment by jerone** [comment]
The published npm version isn't Node v0.12 compatible yet, but it's coming https://github.com/sass/node-sass-middleware/issues/23

**Comment by am11** [comment]
v0.5.0 is just published. :tada: 

```powershell
npm install node-sass-middleware@0.5
```

**Comment by causztic** [comment]
thanks so much!
