### ISSUE TITLE
crashes because of extra indent

### ISSUE THREAD

**Issue by jurgentreep** [sass/node-sass-middleware#67]
Whenever I add an extra indent to my sass code it crashes.
Example code which causes a crash:
```sass
.information
	list-style-type: none
		.icon
			height: 20px
```
Error log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mediabites@0.0.0~prestart: mediabites@0.0.0
6 silly lifecycle mediabites@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle mediabites@0.0.0~start: mediabites@0.0.0
8 verbose lifecycle mediabites@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle mediabites@0.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\mediabites\node_modules\.bin;C:\Users\Administrator\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Administrator\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\nodejs;C:\Program Files\MongoDB\Server\3.2\bin;C:\Users\Administrator\AppData\Roaming\npm;C:\Users\Administrator\AppData\Local\atom\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle mediabites@0.0.0~start: CWD: D:\mediabites
11 silly lifecycle mediabites@0.0.0~start: Args: [ '/d /s /c', 'node ./bin/www' ]
12 silly lifecycle mediabites@0.0.0~start: Returned: code: 3221225477  signal: null
13 info lifecycle mediabites@0.0.0~start: Failed to exec start script
14 verbose stack Error: mediabites@0.0.0 start: `node ./bin/www`
14 verbose stack Exit status 3221225477
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid mediabites@0.0.0
16 verbose cwd D:\mediabites
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v5.5.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error mediabites@0.0.0 start: `node ./bin/www`
22 error Exit status 3221225477
23 error Failed at the mediabites@0.0.0 start script 'node ./bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the mediabites package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/www
23 error You can get their info via:
23 error     npm owner ls mediabites
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by am11** [comment]
Thanks for the report @jurgentreep and more for providing steps to repro! :)

It turned out to be a libsass issue, which has been fixed in master. With current release of node-sass, libsass was getting terminated with `Segmentation fault: 11` (aka sigsegv).

With current master of libsass, I get this response with your code sample:

```json
01:01 $ node bin/node-sass ../meta/issues/nsm-gh-67.sass 
{
  "formatted": "Error: Illegal nesting: Only properties may be nested beneath properties.\n        on line 2 of ../nsm-gh-67.sass\n>>     list-style-type: none {\n   -------------------------^\n",
  "message": "Illegal nesting: Only properties may be nested beneath properties.",
  "column": 26,
  "line": 2,
  "file": "/Users/adeel/github/meta/issues/nsm-gh-67.sass",
  "status": 1
}
```

If you are interested in getting pre-release bits, please follow these steps:

```bash
cd your-project/node_modules
rm -rf node-sass
git clone https://github.com/sass/node-sass --recursive
cd node-sass/src/libsass
git checkout master
cd ../..
npm install
node scripts/build -f
# now your are ready
```

cc @xzyfer

**Comment by jurgentreep** [comment]
Thanks a lot!
I'll make sure to install the latest version.
