### ISSUE TITLE
Installation problem, please help!

### ISSUE THREAD

**Issue by t47io** [sass/node-sass-middleware#78]
I installed `node-sass-middleware` with `npm install -g` and then `npm link` at my work directory. Everything seems fine. But when I try starting my app with `supervisor`, I always get the following error:

```
Running node-supervisor with
  program 'app.js'
  --watch '.'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node app.js'
Watching directory '/Website_Server/t47io/main' for changes.
Press rs for restarting the process.
fs.js:761
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/node-sass-middleware/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at Object.getInstalledBinaries (/usr/local/lib/node_modules/node-sass-middleware/node_modules/node-sass/lib/extensions.js:74:13)
    at foundBinariesList (/usr/local/lib/node_modules/node-sass-middleware/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/usr/local/lib/node_modules/node-sass-middleware/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/usr/local/lib/node_modules/node-sass-middleware/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-sass-middleware/node_modules/node-sass/lib/index.js:14:28)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
Program node app.js exited with code 1
```

I have no idea what's wrong. What should be in that `vendor` folder? My `app.js`: (excerpt)

```
...
var sass = require('node-sass-middleware');
...
app.use( sass({
    'src': path.join(root, 'sass/'),
    'dest': path.join(root, 'css/'),
    'degug': DEBUG
}) );
app.use( express.static(root) );
...
```

How should I fix the `node-sass` install? It is currently `node-sass 3.7.0` and `node-sass-middleware 0.9.8`. Why is the `vendor` folder not set up correctly by `npm install` itself?

**Comment by t47io** [comment]
Never mind, total mess of local node/npm installs.
